import CADModeling
import CADTopology
import SwiftCAD

public typealias AngleUnit = SwiftCAD.AngleUnit
public typealias SubshapeID = SwiftCAD.SubshapeID
public typealias StableSubshapeReference = SwiftCAD.StableSubshapeReference
public typealias SubshapeIndex = SwiftCAD.SubshapeIndex
public typealias TopologyLineage = SwiftCAD.TopologyLineage
public typealias SubshapeGeometrySignature = SwiftCAD.SubshapeGeometrySignature
public typealias ParameterResolver = CADModeling.ParameterResolver
public typealias SweepEvaluationCapabilities = CADModeling.SweepEvaluationCapabilities
public typealias EvaluatedCurve = CADModeling.EvaluatedCurve
public typealias CADExpression = SwiftCAD.CADExpression
public typealias CADAgentMeasurementQuery = SwiftCAD.MeasurementQuery
public typealias CADAgentMeasurementQueryResult = SwiftCAD.MeasurementQueryResult
public typealias CADPipeline = SwiftCAD.CADPipeline
public typealias CADBRepModel = CADTopology.BRepModel
public typealias CADFace = CADTopology.Face
public typealias BodyKind = CADTopology.BodyKind
public typealias BRepModel = CADTopology.BRepModel
public typealias Loop = CADTopology.Loop
public typealias Body = CADTopology.Body
public typealias EvaluatedCurvePathEvaluator = CADModeling.EvaluatedCurvePathEvaluator
public typealias PolySplineMeshAnalyzer = CADModeling.PolySplineMeshAnalyzer
public typealias Face = CADTopology.Face
public typealias Coedge = CADTopology.Coedge
public typealias Edge = CADTopology.Edge
public typealias LoopRole = CADTopology.LoopRole
public typealias Orientation = CADTopology.Orientation
public typealias CurveTrim = CADTopology.CurveTrim
public typealias SurfaceTrimLoop = SwiftCAD.SurfaceTrimLoop
public typealias SurfaceTrimLoopRole = SwiftCAD.SurfaceTrimLoopRole
public typealias SurfaceParameterDomain2D = SwiftCAD.SurfaceParameterDomain2D
public typealias SurfaceTrimFeature = SwiftCAD.SurfaceTrimFeature
public typealias CADProfile = SwiftCAD.Profile
public typealias BSplineSurface3D = SwiftCAD.BSplineSurface3D
public typealias BSplineCurve2D = SwiftCAD.BSplineCurve2D
public typealias BodyID = SwiftCAD.BodyID
public typealias BooleanEvaluationCapabilities = SwiftCAD.BooleanEvaluationCapabilities
public typealias BooleanEvaluationPlanResult = SwiftCAD.BooleanEvaluationPlanResult
public typealias BooleanEvaluationPlanService = SwiftCAD.BooleanEvaluationPlanService
public typealias BooleanEvaluationPreflightCheck = SwiftCAD.BooleanEvaluationPreflightCheck
public typealias BooleanEvaluationTopologyCounts = SwiftCAD.BooleanEvaluationTopologyCounts
public typealias BooleanEvaluationTopologySlot = SwiftCAD.BooleanEvaluationTopologySlot
public typealias BooleanFeature = SwiftCAD.BooleanFeature
public typealias BooleanOperation = SwiftCAD.BooleanOperation
public typealias BooleanTargetReference = SwiftCAD.BooleanTargetReference
public typealias BooleanToolReference = SwiftCAD.BooleanToolReference
public typealias CurveEvaluationSample = SwiftCAD.CurveEvaluationSample
public typealias CurveSubobjectReference = SwiftCAD.CurveSubobjectReference
public typealias EdgeID = SwiftCAD.EdgeID
public typealias EdgeSubobjectReference = SwiftCAD.EdgeSubobjectReference
public typealias EvaluatedDocument = SwiftCAD.EvaluatedDocument
public typealias ExtrudeDirection = SwiftCAD.ExtrudeDirection
public typealias ExtrudeFeature = SwiftCAD.ExtrudeFeature
public typealias FaceID = SwiftCAD.FaceID
public typealias FeatureNode = SwiftCAD.FeatureNode
public typealias FeatureOperation = SwiftCAD.FeatureOperation
public typealias FeatureID = SwiftCAD.FeatureID
public typealias GeneratedSubshapeRole = SwiftCAD.GeneratedSubshapeRole
public typealias LoopID = SwiftCAD.LoopID
public typealias MaterialID = SwiftCAD.MaterialID
public typealias Matrix4x4 = SwiftCAD.Matrix4x4
public typealias Mesh = SwiftCAD.Mesh
public typealias ParameterTable = SwiftCAD.ParameterTable
public typealias Point2D = SwiftCAD.Point2D
public typealias Point3D = SwiftCAD.Point3D
public typealias PolySplineMeshAnalysisResult = SwiftCAD.PolySplineMeshAnalysisResult
public typealias PolySplineOptions = SwiftCAD.PolySplineOptions
public typealias ProfileReference = SwiftCAD.ProfileReference
public typealias Quantity = SwiftCAD.Quantity
public typealias QuantityKind = SwiftCAD.QuantityKind
public typealias RevolveAxis = SwiftCAD.RevolveAxis
public typealias RevolveFeature = SwiftCAD.RevolveFeature
public typealias SelectionDimensionEvaluation = SwiftCAD.SelectionDimensionEvaluation
public typealias SelectionDimensionID = SwiftCAD.SelectionDimensionID
public typealias SelectionDimensionKind = SwiftCAD.SelectionDimensionKind
public typealias SelectionReference = SwiftCAD.SelectionReference
public typealias SelectionMeasurementPoint = SwiftCAD.SelectionMeasurementPoint
public typealias SelectionDistanceMeasurement = SwiftCAD.SelectionDistanceMeasurement
public typealias SelectionAngleMeasurement = SwiftCAD.SelectionAngleMeasurement
public typealias SketchConstraint = SwiftCAD.SketchConstraint
public typealias Sketch = SwiftCAD.Sketch
public typealias SketchArc = SwiftCAD.SketchArc
public typealias SketchCircle = SwiftCAD.SketchCircle
public typealias SketchEntity = SwiftCAD.SketchEntity
public typealias SketchEntityID = SwiftCAD.SketchEntityID
public typealias SketchLine = SwiftCAD.SketchLine
public typealias SketchPlane = SwiftCAD.SketchPlane
public typealias SketchPoint = SwiftCAD.SketchPoint
public typealias SketchReference = SwiftCAD.SketchReference
public typealias SketchSpline = SwiftCAD.SketchSpline
public typealias SketchSplineEndpoint = SwiftCAD.SketchSplineEndpoint
public typealias ModelingTolerance = SwiftCAD.ModelingTolerance
public typealias FeatureEvaluating = CADModeling.FeatureEvaluating
public typealias EvaluationContext = CADModeling.EvaluationContext
public typealias EvaluationResult = CADModeling.EvaluationResult
public typealias SketchSplineEndpointReference = SwiftCAD.SketchSplineEndpointReference
public typealias SketchTangencyConstraint = SwiftCAD.SketchTangencyConstraint
public typealias SketchSplineLineTangencyConstraint = SwiftCAD.SketchSplineLineTangencyConstraint
public typealias SketchSplineEndpointTangencyConstraint = SwiftCAD.SketchSplineEndpointTangencyConstraint
public typealias SketchTangentOrientation = SwiftCAD.SketchTangentOrientation
public typealias SketchCurveSampler = SwiftCAD.SketchCurveSampler
public typealias SweepFeature = SwiftCAD.SweepFeature
public typealias LoftFeature = SwiftCAD.LoftFeature
public typealias LoftGuideReference = SwiftCAD.LoftGuideReference
public typealias LoftSectionReference = SwiftCAD.LoftSectionReference
public typealias LoftOptions = SwiftCAD.LoftOptions
public typealias LoftResultKind = SwiftCAD.LoftResultKind
public typealias LoftSectionMatching = SwiftCAD.LoftSectionMatching
public typealias LoftSectionSmoothTangentMode = SwiftCAD.LoftSectionSmoothTangentMode
public typealias LoftSurfaceMode = SwiftCAD.LoftSurfaceMode
public typealias SweepCurveSectionReference = SwiftCAD.SweepCurveSectionReference
public typealias SweepGuideReference = SwiftCAD.SweepGuideReference
public typealias SweepOptions = SwiftCAD.SweepOptions
public typealias SweepPathReference = SwiftCAD.SweepPathReference
public typealias SweepSectionReference = SwiftCAD.SweepSectionReference
public typealias SweepTargetReference = SwiftCAD.SweepTargetReference
public typealias SweepAlignment = SwiftCAD.SweepAlignment
public typealias SweepBooleanOperation = SwiftCAD.SweepBooleanOperation
public typealias SweepCornerStyle = SwiftCAD.SweepCornerStyle
public typealias SweepGuideMethod = SwiftCAD.SweepGuideMethod
public typealias SweepResultKind = SwiftCAD.SweepResultKind
public typealias SweepEvaluationPlanResult = SwiftCAD.SweepEvaluationPlanResult
public typealias SweepEvaluationPlanService = SwiftCAD.SweepEvaluationPlanService
public typealias SweepEvaluationPreflightCheck = SwiftCAD.SweepEvaluationPreflightCheck
public typealias SurfaceControlPointReference = SwiftCAD.SurfaceControlPointReference
public typealias SurfaceParameter = SwiftCAD.SurfaceParameter
public typealias SurfaceParameterCurve = SwiftCAD.SurfaceParameterCurve
public typealias SurfaceParameterReference = SwiftCAD.SurfaceParameterReference
public typealias SurfaceReference = SwiftCAD.SurfaceReference
public typealias SurfaceSubobjectReference = SwiftCAD.SurfaceSubobjectReference
public typealias SurfaceTrimKnotReference = SwiftCAD.SurfaceTrimKnotReference
public typealias SurfaceTrimReference = SwiftCAD.SurfaceTrimReference
public typealias SurfaceTrimSpanReference = SwiftCAD.SurfaceTrimSpanReference
public typealias TopologyReference = SwiftCAD.TopologyReference
public typealias Transform3D = SwiftCAD.Transform3D
public typealias Vector3D = SwiftCAD.Vector3D
public typealias VertexID = SwiftCAD.VertexID

public enum SurfaceTrimEndpoint: String, Codable, CaseIterable, Equatable, Sendable {
    case start
    case end
}

public extension SketchPlane {
    static var defaultWorkspacePlane: SketchPlane {
        .xy
    }
}
